### ISSUE TITLE
Possible issue on String params  (introduced padding is counted in length field of AVP)

### ISSUE THREAD

**Issue by albertpv** [RestComm/jdiameter#119]
When i create an AVP with following code:
```
AvpSet myAvpSet 

            requestAvps.addAvp(547, "mcpttp".getBytes(), vendorID, false, false); // MCPTT-Identifier
```

I understand padding has to be added but the length the stack sends for this AVP seems to be the full length +padding and not the length of the AVP.

See attached screenshot 

What i would like is : length we send for that AVP is just the length of the AVP without counting the padding.

What can i do to fix this problem? (can i override some method or class to specify length field value we will send  for an AVP)

If that is not possible  why is it correct padding is counted for length field of the AVP ?  Which is the reference doc for that?

Thanks!
![image 1](https://user-images.githubusercontent.com/1034232/33388946-b0336b3e-d531-11e7-8afe-3e9ef7b3edfc.png)

**Comment by aferreiraguido** [comment]
@albertpv if you code the 3 bytes length of an AVP against the Diameter IETF standard, you'll be having rejected packets. Please double check Diameter writings in the attached picture. So far... you got four bytes of code, one byte for flags, three bytes for length, four more bytes for vendor id and the final value which seems six-octet length, so you require the extra two bytes of padding to have a multiple of four-octets in length, counting eighteen octet value.

If the problem is to transform back to a simple and single string object, you can use some regex tricks, like the following snippet. Also note that - eventually - within an utf8-avp-value, you could send two or more strings zero terminated, and that would be absolutely valid.

byte[] octetAvp547String = received_avpset.getAvp(547).getUTF8String();
String my_547_value = new String(octetAvp547String).split("\0")[0];

![image](https://user-images.githubusercontent.com/16017135/33438197-defd6d42-d5c8-11e7-8f55-91ddc4c2c913.png)

**Comment by gsaslis** [comment]
thanks for taking this up @aferreiraguido !! 👍 

@albertpv did that help answer your issue? can I mark this as closed?

**Comment by albertpv** [comment]
Hi @aferreiraguido  and @gsaslis 
OK the explanation sounds clear and you are right for the AVP I said all is send correctly
But now i understood better my issue:

Problem is that if the OctetString AVP contains spaces then the length the stack sends includes the nitroduced padding.

See example:

The problem is I do not control the other endpoint hence if length is send wrong we cannot fix / remove padding easily
See attached example:

Here is code how i add the AVP:
submed.addAvp("permit in 17 from 10.41.160.2 10154 to 10.1.1.218 26492".getBytes("UTF8),vendorID,true,false);

Attached the network trace of  just 1 frame with the AAR sent by JDiameter  ("problem" i mention can be seen inside second flow description of the Media SubComponent (AVP 519)

See attached network trace and screnshot showing how wireshark not detects properly padding.

Thanks for your input!

[paddingIssueTrace.pcap.zip](https://github.com/RestComm/jdiameter/files/1550775/paddingIssueTrace.pcap.zip)
![diameter](https://user-images.githubusercontent.com/1034232/33874931-d395d6d6-df20-11e7-87d9-7fce59dac1f0.png)

**Comment by albertpv** [comment]
Finally discovered and fixed the issue . It was in a  method getWholeAVPs not part of jdiameter project....so i am not sure anymore it is a fault on the stack and close this issue. (Anyway would be nice to test it)

**Comment by gsaslis** [comment]
@albertpv thanks so much for reporting back and closing the issue. 

Would you mind opening a new issue for the new problem you're facing?

**Comment by albertpv** [comment]
yeah no problem :-) i did not open just because i am not sure it is a bug or just i am misusing something.
