### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by aangeloff** [RestComm/jdiameter#145]
I want to use the jDiameter library with log4j2. I see most of the classes uses slf4j for logging, but 19 classes still uses log4j 1.x for logging
It will be nice to migrate all (or at least ProxyAgentImpl.java and AvpDictionary.java) classes to slf4j.

There are the classes that still uses log4j 1.x:
core\jdiameter\impl\src\main\java\org\jdiameter\server\impl\agent\ProxyAgentImpl.java
core\mux\jar\src\main\java\org\mobicents\diameter\dictionary\AvpDictionary.java

examples\charging-server-simulator\src\main\java\org\mobicents\servers\diameter\utils\DiameterUtilities.java
examples\charging-server-simulator\src\main\java\org\mobicents\servers\diameter\utils\StackCreator.java
examples\guide1\src\main\java\org\example\client\ExampleClient.java
examples\guide1\src\main\java\org\example\server\ExampleServer.java
testsuite\load\container\src\main\java\org\mobicents\diameter\server\bootstrap\Main.java
testsuite\load\container\src\main\java\org\mobicents\diameter\server\bootstrap\MainDeployer.java
testsuite\load\core\src\main\java\org\mobicents\tests\diameter\AbstractStackRunner.java
testsuite\load\core\src\main\java\org\mobicents\tests\diameter\CLIRunner.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\StackConnectDelayTest.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\StackConnectMultiBaseTest.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\StackConnectTest.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\StackReConnectionTest.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\dictionary\MessageValidatorTest.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\functional\StackCreator.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\functional\TBase.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\functional\Utils.java
testsuite\tests\src\test\java\org\mobicents\diameter\stack\functional\acc\base\AccSessionFTFlowTest.java

**Comment by StephenDwyer-kcom** [comment]
I was about to raise this same issue, but found that @aangeloff had raised exactly this.

Can this please be given a higher priority and addressed ASAP? It's a real blocker for those users needing to use log4j 2 behind the slf4j facade.

In the classes mentioned above (with ProxyAgentImpl and AvpDictionary being the most critical - the others being example & testsuite code) there's been a hardcoded dependency inadvertently created to the log4j 1 library. The fix is easy, as outlined below (we've fixed this provisionally on a clone from the repo, but prefer to use an official Restcomm release in our production releases).

package org.jdiameter.server.impl.agent;

change:
import org.apache.log4j.Logger;
to:
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

...
public class ProxyAgentImpl extends AgentImpl implements IProxy {

change:
  private static Logger logger = Logger.getLogger(ProxyAgentImpl.class);
to:
  private static Logger logger = LoggerFactory.getLogger(ProxyAgentImpl.class);
