### ISSUE TITLE
Improve performance of Netty Stack

### ISSUE THREAD

**Issue by deruelle** [RestComm/jdiameter#47]
Follow up from https://github.com/RestComm/jdiameter/issues/35

**Comment by jehanzebqayyum** [comment]
@brainslog may i know the details of the load test you did for netty tcp?

**Comment by deruelle** [comment]
@jehanzebqayyum you can see it described here http://documentation.telestax.com/core/tutorials/jdiameter-quick-telscale-diameter-performance-testing-using-seagull.html

**Comment by jehanzebqayyum** [comment]
Did some initial testing.

1000 calls/sec and 1 min of test each.
JAVA_OPTS = -Xms512m -Xmx1024m
machine (4GB, i5 @ 2.6GHz x 4).

Netty
 Successful calls=55198
 Failed calls=222
NIO
 Successful calls=57817
 Failed calls=41

More than 1000 call rate, failure/timeout counts increases. 

P.S:
charging-server-simulator-perf-test/pom.xml dependency needed minor correction: 
from
 <artifactId>mobicents-diameter-mux-jar</artifactId>
to
 <artifactId>restcomm-diameter-mux-jar</artifactId>

**Comment by deruelle** [comment]
@jehanzebqayyum Thanks. feel free to do a Pull Request on restcomm-diameter-mux-jar and investigate what is the blocker for call rate. 
I think you can use https://github.com/RestComm/PerfCorder and @jaimecasero could potentially give you some hints to set it up to record all utilization about the test on memory CPU etc.

**Comment by jehanzebqayyum** [comment]
I see many TCP window size zero messges in wireshark trace. Seems like i
need to adjust tcp settings as both client and server on same machine are
eating tcp stack mem.

On Jul 15, 2016 7:11 PM, "Jean Deruelle" <notifications@github.com> wrote:
>
> @jehanzebqayyum Thanks. feel free to do a Pull Request on
restcomm-diameter-mux-jar and investigate what is the blocker for call
rate.
> I think you can use https://github.com/RestComm/PerfCorder and
@jaimecasero could potentially give you some hints to set it up to record
all utilization about the test on memory CPU etc.

**Comment by jehanzebqayyum** [comment]
Updating tcp stack settings as below to max 64MB buffer per socket had no effect, since RAM maxed during the test to 97% so not enough memory.

sudo sysctl -w net.core.rmem_max=64777216
sudo sysctl -w net.core.wmem_max=64777216
sudo sysctl -w net.ipv4.tcp_rmem='87380 16777216 64777216'
sudo sysctl -w net.ipv4.tcp_wmem='87380 16777216 64777216'
sudo sysctl -w net.ipv4.route.flush=1

seagull client randomly gave below error which is mentioned in FAQ
http://gull.sourceforge.net/doc/faq.html#faq006

send failed [-1] [Resource temporarily unavailable]
Flow control not implemented

I see seagull client sending TCP ZeroWindow usually in response to the jdiameter server sending TCP Window Full. The jdiameter server usually replies with huge no. of Diameter messages (32k) in single TCP segment.
Seems like cannot go beyond call rate=1000 msg/sec with failures of around ~500 per min with my current memory.

**Comment by brainslog** [comment]
Hi @jehanzebqayyum,

What is the available RAM you have setup for the JVM ? I think you should be able to go over 1000 req/s with little memory usage (<1GB).

Try to set RequestTable sizes to 0 (@ https://github.com/RestComm/jdiameter/blob/master/core/mux/common/config/jdiameter-config.xml#L60) in order not to keep so much memory occupied (this way routing info is kept in the answer object, and once that's gone it will clear, also saving CPU on table lookup/cleanup).

The generally observed scenario is that no CPU or MEM maxes out, still seagull is unable to send further requests with the same error you are observing. So it looks like an I/O issue, thus I was expecting netty could help on this, but so far it hasn't yet reached the same level. Maybe figuring the culprit for this will help finding out the same for NIO.

**Comment by jehanzebqayyum** [comment]
I was able to reach 5000 call-rate by modifying seagull config as below i.e. 
Giving seagull more time for IO instead of displaying stats and allowing seagull itself to control other parameters such max-simultaneous-calls etc.

 <define entity="traffic-param" name="call-rate" value="5000"></define>
  <define entity="traffic-param" name="display-period" value="8"></define>
  <define entity="traffic-param" name="log-stat-period" value="8"></define>

**Comment by brainslog** [comment]
@jehanzebqayyum, nice increase you got there, any difference between NIO and Netty ? Also, can you share the config parts you've changed, so that I can try to replicate ? Thanks!

**Comment by jehanzebqayyum** [comment]
Netty puts more load on memory with default options since it uses PooledByteBufAllocator, which decrease servers capability to handle more messages with same memory as that of NIO. The netty server thus advertises lesser TCP Window Size. But of course this means improved CPU performance. The option is configurable and we may use UnpooledByteBufAllocator.

I have always seen in wirehsark TCP Window Zero from seagull to server meaning client is unable to receive more messages. I therefore played with seagull configuration (see attached). With these changes i see call-rate improvements (NIO~8k and Netty~6.5k) and no TCP Window Zero messages.

I have also done some minor improvements in netty impl (pull request soon) for your test :)

[conf.client.xml.txt](https://github.com/RestComm/jdiameter/files/377730/conf.client.xml.txt)

**Comment by deruelle** [comment]
@brainslog were you able to review @jehanzebqayyum work ?

**Comment by brainslog** [comment]
Thanks @jehanzebqayyum. With instructions from #52 and this I was able to achieve good call rates (12~15K msg/sec), although after some time it'll start failing a few requests. I'm not sure this is related to netty or if it is a common structure that might be breaking, as I think I saw it with NIO as well, although after a bit more time & load. I will need to run a long and slow test to confirm what's happening.

NIO still remains more stable (in CPU utilization, less peaks, less GC runs/time, etc) and I think we can still improve netty, but so far it is already in a good shape, nice work!

**Comment by santosh135** [comment]
I was load testing the Netty build of Jdiameter and got , 22k-23k TPS. still trying to improve the numbers.

while going through the code, TcpClientConnection , i found that in onEvent function when an event e.g. message received is raised, all the connection listeners are called in blocking. any specific reason for it ? 

increasing the thread-group size in jdiameterconfig.xml doesnt seem to affect the no of active threads. why? 

meanwhile i am trying to tune the netty parameters.

**Comment by jehanzebqayyum** [comment]
Hi,


If you see netty.TCPTransportClient, the msgHandler in the pipeline has
different eventExecutorGroup assigned. It's current size is 1 thread which
can be adjusted.

**Comment by santosh135** [comment]
@deruelle  pls find inline

_How long did you run the test for ?_
around 8-10 hours

_Feel free to experiment with async/non blocking on listeners and report back_
i did , removed the lock, performance actually went down by 1k TPS

_Feel free to investigate the thread-group size issue as well._
still doing it, but it has no impact on TPS, still cant go beyond 22k, i guess bottleneck is somewhere else. please suggest what could be the reason, meanwhile i am examining thread model.

i was bench-marking netty , jmeter reported 220k transactions per second.  

@jehanzebqayyum i experimented with that as well, but observed no major improvement.

**Comment by ammendonca** [comment]
Closing this as current netty implementation performs similar to NIO (with somewhat better response times).

Thanks @jehanzebqayyum!
